# These are supported funding model platforms

github: # Replace with GitHub username/org if sponsorship is enabled
patreon: # Replace with Patreon username
open_collective: # Replace with Open Collective project name
custom: ["https://github.com/sponsors"]
